### ISSUE TITLE
Using scriptcs instead of cscs

### ISSUE THREAD

**Issue by Nicolas01** [oleg-shilo/cs-script.vscode#13]
I use [scriptcs](http://scriptcs.net/) because it allows to write scripts without basic using, main class and main static method.  
The following code works without using, class or method:

> Console.WriteLine("Hello");

As I like very much you extension, because it allows to code and debug in vscode, I would like also to use scriptcs with your extension.  
Do you think there is any way to replace the call of `cscs` by `scriptcs`? And do you think the debugging feature still work?

> mono C:\ProgramData\chocolatey\bin\scriptcs.exe .\script.cs

**Comment by oleg-shilo** [comment]
Sorry for misunderstanding. 

CS-Script is a mature scripting solution that has been around for quite a while. I have developed it ~14 years ago. Arguably it is today the most advanced/mature C# scripting solution available. It has been a vital part of quite a few main stream products (e.g. FlashDevelop, MediaPortal). It also has been integrated with Notepad++, Sublime Text 3 and Visual Studio 2013/15/17. It is also is the engine behind WixSharp - C# binding for WiX. 

You can find all the information about it on GitHub: https://github.com/oleg-shilo/cs-script. 

Thus, probably it does not fully deserve to be called "odd"  :)
Though of course this can be debated.

If you wish to use simplified classless scripts you can do this as below: 

```C#
//css_args -autoclass
using System;

void main()
{
    Console.WriteLine("Hello...");
}
```

**Comment by Nicolas01** [comment]
Thanks for your answer.  
Is there a way, like autoclass, to inject basic usings and main method?

**Comment by oleg-shilo** [comment]
Yes there is. You can use _precompiler script_. The distro comes with the "freestyle" sample:

```C#
//css_precompiler freestyle
using System.Windows.Forms;
 
for (int i = 0; i < args.Length; i++)
{
    Console.WriteLine(args[i]);
}

MessageBox.Show(Path.GetDirectoryName(Environment.CurrentDirectory), "Hello World!");
```
[Precompilers.zip](https://github.com/oleg-shilo/cs-script.vscode/files/2306200/Precompilers.zip)

Though I am almost positive that Mono debugger will not be able to handle the breakpoints correctly and without an extra adjustment to the extension implementation is required. 

Please log the feature request and I will have a look at it. I am planing to release the extension update with the latest CS-Script engine the next week anyway. Thus it will be a good opportunity to add any new features.

**Comment by Nicolas01** [comment]
Awesome, it was exactly what I was looking for!
Unfortunately the debug feature doesn't works anymore if I use `css_precompiler`.    
The breakpoints are not hit.  
Maybe you can do as you did with autoclass: display the newly generated script and break at the first line.

**Comment by oleg-shilo** [comment]
The change required for debugging is simple but yet it needs to be delivered in the way that it does not affect the Intellisense. If you only want to enable debugging you don't need to wait. Just replace the content of the _freestyle.cs_ precompiler with the code below:
```C#
using System;
using System.Collections;
using System.Text;
using System.IO;

public class AutoclassPrecompiler
{
    static public bool Compile(ref string content, string scriptFile, bool IsPrimaryScript, Hashtable context)
    {
        if (!IsPrimaryScript)
            return false;

        StringBuilder code = new StringBuilder();
        code.AppendLine("//Auto-generated file");
        code.AppendLine("using System;");
        code.AppendLine("using System.IO;");

        bool headerProcessed = false;

        string line;
        int lineIndex = 0;

        using (StringReader sr = new StringReader(content))
            while ((line = sr.ReadLine()) != null)
            {
                //not using...; statement of the file header
                if (!headerProcessed && !line.TrimStart().StartsWith("using "))
                    if (!line.StartsWith("//") && line.Trim() != "") //not a comment/empty line
                    {
                        headerProcessed = true;

                        code.AppendLine("   public class ScriptClass");
                        code.AppendLine("   {");
                        code.AppendLine("       static public int Main(string[] args) { return main_impl(args); }");
                        code.AppendLine("#line " + (lineIndex - 1) + " \"" + scriptFile + "\"");
                        code.AppendLine("       static public int main_impl(string[] args)");
                        code.AppendLine("       {");
                    }

                code.Append("/*" + lineIndex.ToString("D6") + "*/" + line);
                code.Append(Environment.NewLine);
                lineIndex++;
            }

        code.AppendLine("       return 0;");
        code.AppendLine("   }");
        code.AppendLine("}");

        content = code.ToString();
        return true;
    }
}
```

And ensure that your precompiler is always found. Do this either by adding the prcompiler script directory to the both settings files (Ctrl+Shift+P):
![image](https://user-images.githubusercontent.com/16729806/44621009-34666080-a8e2-11e8-9b8f-12c9f7abcf43.png)

```xml
...
<searchDirs>your precompiler dir;%CSSCRIPT_DIR%\lib;%CSSCRIPT_INC%;%MONO%/4.5/Facades</searchDirs>
...
```

Now just place the breakpoint in your code and start the debugging:

![image](https://user-images.githubusercontent.com/16729806/44621038-9d4dd880-a8e2-11e8-9382-f8ead636df1a.png)

**Comment by oleg-shilo** [comment]
Reopened as an enhancement.

**Comment by oleg-shilo** [comment]
The latest release v1.5.7 has been published on Marketplace.

**Comment by Nicolas01** [comment]
Thanks a lot, writing small scripts is really easier now and the debug works great in VS code.
