### ISSUE TITLE
Will there be a cs-script.core.vscode ?

### ISSUE THREAD

**Issue by frankhommers** [oleg-shilo/cs-script.vscode#16]
Are you planning on releasing a cs-script.core.vscode?

I already have dotnet core on my machine, installing mono for cs-script.vscode feels like overkill ;-)

**Comment by oleg-shilo** [comment]
Absolutely. It is the very next step. I am a little behind with my other projects but now catching up quickly. So I do expect to deal with this one in within a month or so.
