### ISSUE TITLE
Extension do not work

### ISSUE THREAD

**Issue by martasp** [oleg-shilo/cs-script.vscode#18]
Dependencies are instaled but the extension doesn't work. 
`
mono : The term 'mono' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
`
+ mono "C:\Users\mart\AppData\Roaming\Code\User\cs-script.user\cscs.exe ...
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (mono:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by oleg-shilo** [comment]
Can you check that you have Mono installed as well as MonoDebugger VSCode extension.
They are the prerequisites for CS-Script extension.
