### ISSUE TITLE
How to Run CSScript in VSCode using lastest Extension

### ISSUE THREAD

**Issue by AlGantori** [oleg-shilo/cs-script.vscode#19]
<html>
<body>
<h1>How to Run CSScript in VSCode</h1>
20200215
<h3>Goals</h3>
<ol>
	<li>It's been a while, can't remember how to run it, and it does not look it 
	wants to run</li>
	<li>Last used successfully in VSCode was around
20180517
</li>
</ol>
<h2>Extensions Installed?</h2>
<ol>
	<li>It appears my VSCode has both of them<br>

![image](https://user-images.githubusercontent.com/11699920/74601393-c9b76080-5052-11ea-88e8-279ca858d815.png)
>
<br>
	<br>
	
![image](https://user-images.githubusercontent.com/11699920/74601408-f1a6c400-5052-11ea-9cc1-e783eb525202.png)
<br>
&nbsp;</li>
	<li>The Toolbar appears as soon as I switch these particular .CS files, 
	That's NICE !!!<br>
	
![image](https://user-images.githubusercontent.com/11699920/74601415-1307b000-5053-11ea-8d92-8eabb4f45d5b.png)
</li>
	<li>But the Run button produces the following error:<br>

![image](https://user-images.githubusercontent.com/11699920/74601623-01270c80-5055-11ea-937f-406b1301ea02.png)

</li>
</ol>
<h3>but CS-Script has External? Dependencies...Requirements...</h3>
<ol>
	<li>Back in 2018 for the first time in VSCode the Mono was<br>
	<span style="background-color: #FFFF00">The latest Stable Mono release is:
	</span><strong><span style="background-color: #FFFF00">5.12.0 Stable 
	(5.12.0.226)<br>
	<br>
	</span>
	</strong>I am definitely behind...<br>
&nbsp;</li>
	<li><a href="http://www.mono-project.com/download/stable/">Download - Stable 
	| Mono</a> <br>
	<span style="background-color: #FFFF00">The latest Stable Mono release is:
	</span><strong><span style="background-color: #FFFF00">6.8.0 Stable 
	(6.8.0.105)</span><br>
	
![image](https://user-images.githubusercontent.com/11699920/74601465-96c19c80-5053-11ea-8906-5de7e74b6cb5.png)
</strong></li>
	<li>I downloaded mono-6.8.0.105-x64-0.msi <strong>Installed it</strong></li>
        <li><strong>No mention whether GTK version? is needed, I forgot what GTK stands for :)</strong></li>
	<li>Verified
	<span style="background-color: #FFFF00">C:\Program Files\Mono\bin\ </span>is 
	still on the path from previous setup....<br>
	ECHO %PATH% &gt;&gt; TMP.TXT<br>
	<br>
	
![image](https://user-images.githubusercontent.com/11699920/74601497-ebfdae00-5053-11ea-8a78-1fe33d324465.png)
<br>
&nbsp;</li>
</ol>
<h3>My real problem is probably CSCS.EXE is NOT on the path</h3>
<ol>
	<li>Searching C:\ reveals the following:<br>
	<br>
	
![image](https://user-images.githubusercontent.com/11699920/74601501-f750d980-5053-11ea-9328-1f3117ae0c7f.png)
<br>
&nbsp;</li>
	<li>So which one should I use?<ol>
	<li><a href="file:///C:/Users/AXM/AppData/Roaming/Code/User/cs-script.user">
	C:\Users\AXM\AppData\Roaming\Code\User\cs-script.user</a></li>
	<li>
	<a href="file:///C:/Users/AXM/.vscode/extensions/oleg-shilo.cs-script-1.5.10/bin">
	C:\Users\AXM\.vscode\extensions\oleg-shilo.cs-script-1.5.10\bin</a> <br>
&nbsp;</li>
	<li>Why wasn't it installed?&nbsp; <br>
	Perhaps VSCode extension can't do that?</li>
	<li><br>
	<br>
&nbsp;</li>
</ol></li>
	<li>Computer Properties...<br>
	
![image](https://user-images.githubusercontent.com/11699920/74601510-0f285d80-5054-11ea-8105-ceb0e82f502b.png)
</li>
</ol>
<h3>User Variable</h3>
<ol>
	<li>It was set to:<ol>
	<li><br>
	C:\PHP;C:\Ruby22-x64\bin;C:\ProgramData\Oracle\Java\javapath;C:\Chocolatey\bin;<span style="background-color: #FFFF00">C:\Users\AXM\AppData\Roaming\scriptcs</span>;C:\Program 
	Files\Microsoft VS Code\bin;C:\Users\AXM\AppData\Roaming\npm</li>
</ol></li>
	<li>Replaced with:<ol>
	<li>C:\PHP;C:\Ruby22-x64\bin;C:\ProgramData\Oracle\Java\javapath;C:\Chocolatey\bin;<span style="background-color: #FFFF00">C:\Users\AXM\AppData\Roaming\Code\User\cs-script.user</span>;C:\Program 
	Files\Microsoft VS Code\bin;C:\Users\AXM\AppData\Roaming\npm</li>
</ol></li>
	<li>Then replaced with<ol>
	<li>C:\PHP;C:\Ruby22-x64\bin;C:\ProgramData\Oracle\Java\javapath;C:\Chocolatey\bin;<a href="file:///C:/Users/AXM/.vscode/extensions/oleg-shilo.cs-script-1.5.10/bin"><span style="background-color: #FFFF00">C</span><span style="background-color: #FFFF00">:\Users\AXM\.vscode\extensions\oleg-shilo.cs-script-1.5.10\bin</span></a>;C:\Program 
	Files\Microsoft VS Code\bin;C:\Users\AXM\AppData\Roaming\npm</li>
	<li></li>
</ol></li>
</ol>
<h3>System Variables</h3>
<ol>
	<li>It was set to:<ol>
	<li><br>
	C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Program 
	Files\Java\jdk1.7.0_03\bin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program 
	Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files 
	(x86)\QuickTime\QTSystem\;%JAVA_HOME%\bin;%ADT_HOME%\tools;%ADT_HOME%\platform-tools;%ANT_HOME%\bin;%GIT_HOME%\cmd;C:\Program 
	Files\Microsoft\Web Platform Installer\;%systemroot%\System32\WindowsPowerShell\v1.0\;<span style="background-color: #FFFF00">C:\Program 
	Files\Mono\bin</span>;C:\Program Files\dotnet\;C:\Program Files\Microsoft 
	SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft 
	SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program 
	Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft VS Code\bin;C:\Program 
	Files\nodejs\;C:\Program Files\Git\cmd</li>
</ol></li>
	<li>DID NOT TOUCH</li>
	<li>This is kind of a mess, I need an app to manage these vertically, one 
	path per line</li>
</ol>
<h3>Seems like the Path fixed something but not quite CS-Script is still 
crashing...</h3>
<ol>
	<li>Check Syntax works</li>
	<li>I get to run once but with the following error<br>
	
![image](https://user-images.githubusercontent.com/11699920/74601520-1cdde300-5054-11ea-9113-a6c0e34cdc9e.png)
</li>
	<li>my main is practically empty.<br>
&nbsp;</li>
</ol>

![INDEX 79](https://user-images.githubusercontent.com/11699920/74601766-70513080-5056-11ea-8b46-7c2054f3028e.jpg)

.END.
Something wrong with GitHub issues, pasting pictures fails to display some the pictures, instead
it displays the link only (preview and after posting) weird.  
It takes several attempts then sometime it requires drag and drop .
</body>
</html>

**Comment by oleg-shilo** [comment]
Sorry, I'll need some time to get through the info you provided. And answer all your questions one by one. 

But something has definitely changed in VSCode. The extension is broken now and it has nothing to do with the extension itself as it has not been changed since Mar 18, 2019. Though unfortunately it's not so uncommon with VSCode. :(

Will have a look tomorrow

**Comment by oleg-shilo** [comment]
I think I have found it. 

The problem is quite nasty. It was introduced by the changes in the latest/later version of VSCode. However the problem itself is ultimately caused by the ugly nature of JS runtime, not by the VSCode team changes.  

This is what happens:

CS-Scriprt.vscode had this line of code:
```ts
let exec = require("child_process").exec;
. . .
process = exec(command);
```

Note that I missed it and did not use neither `var` nor `let`, what is of course is totally legal in JS. 
It worked in prev versions of VSCode but I am guessing recently VSCode team introduced global variable `process`:
![image](https://user-images.githubusercontent.com/16729806/74652195-96eba480-51d9-11ea-8581-6140096b9d7e.png)
Meaning that the extension really messes up with the IDE. And it does it so spectacularly that the instance of IDE being debugged crashes completely. This way (under debugger) I was able to pinpoint the offending code line.

Fixing the declaration as below has done the trick:
```ts
let exec = require("child_process").exec;
. . .
var process = exec(command); // it's local variable now
```
The version v1.5.11 should be OK now

**Comment by AlGantori** [comment]
A quick test make it a fix.  It looks like you are understanding and doing a **great job** with all this JS stuff :)
I jumped into Ionic framework and TypeScript couple years ago, and I dumped all the promises of Microsoft for cross-platform development just to find more headaches :).  On the upside I only have to deal in general with three things HTML,  TS and CSS.

May I point out few suggestions.
(A) Include the extension version and date somewhere here as it is hard to spot in the extension list.
![image](https://user-images.githubusercontent.com/11699920/74696796-a9e87f80-51ad-11ea-9ae2-64ff1b3e9be8.png)

(B) Please put a heading into the main GitHub page  **"Documentation / Help"** I eventually found the mention to look into the cscs.exe command line help. 
I was after directives.

So it looks like define/option CS_SCRIPT is not longer around?  I doubt it's something I created?
From what I can recall I was using it to switch between debug stepping the script and my assemblies from Visual Studio 2013 then.  Also handling things like MessageBox either coming from Winforms or WPF.
For today's run I had the remove the Not/Bang  "!" as in:
`#if ! CS_SCRIPT`
to get it to compile in VSCode.

![image](https://user-images.githubusercontent.com/11699920/74696727-6e4db580-51ad-11ea-9668-99edcaf0a18f.png)

Does VSCode pickup the location of CSScript extension from the path?
Is the path something that has to be re-adjusted with every update/revision?
`C:\Users\AXM\.vscode\extensions\oleg-shilo.cs-script-1.5.11\bin`

Thank you for all the assistance and effort into this.

**Comment by oleg-shilo** [comment]
Now, let's answer our questions:

- A _"Include the extension version and date somewhere"_
It's not easy as the banner is composed by VSCode and the extension developer has very limited control over the banner content. For some reason VSCode guys decided that showing the version is not helpful. 
However the version can still be accessed via the Chenelog tab:
![image](https://user-images.githubusercontent.com/16729806/74711245-9efa2180-5277-11ea-8230-105df15a570a.png)

And starting from the next release the changelog will include dates. All is prepared for that: [CHANGELOG.md](https://github.com/oleg-shilo/cs-script.vscode/blob/master/CHANGELOG.md). Good suggestion.

- B
Yep. Good idea. Will be available in the next release:

**Comment by AlGantori** [comment]
Thanks for all the answers and additions. 
Regarding the path one more clarification is needed. It does not appear the installation/update of the extension adjusts the system env. variable path and since
VSCode will use path #1 above, then that's the one I need to manually fix my system path with, it appears stable.  This is just in case I need cscs.exe from the command line, really no plan for that.

Sorry about path #3, that was remnants from my first days with CSScript plugin in NPP.  I no longer intend to use CSScript from NPP with VSCode being around, so I have deleted manually that plugin.

You may close this issue with this bit of info as it completes the title of this issue.
Thanks again.

**Comment by oleg-shilo** [comment]
>It does not appear the installation/update of the extension adjusts the system env. variable path and since...

It does not use custom envars it starts the process with an absolute path:
```ts
export function user_dir(): string {
    let extensionRoot = path.dirname(path.dirname(path.dirname(__dirname)));
    let isPortable = path.basename(extensionRoot).toLowerCase() == "data" || path.basename(extensionRoot).toLowerCase() == "code-portable-data";

    if (!_user_dir) {

        if (isPortable) {
            _user_dir = path.join(extensionRoot, 'user-data', 'cs-script.user');
        } else {
            if (os.platform() == 'win32') { // win
                _user_dir = path.join(process.env.APPDATA, 'Code', 'User', 'cs-script.user');
            }
            else if (os.platform() == 'darwin') { // mac
                _user_dir = path.join(process.env.HOME, 'Library', 'Application Support', 'Code', 'User', 'cs-script.user');
            }
            else { // linux
                _user_dir = path.join(process.env.HOME, '.config', 'Code', 'User', 'cs-script.user');
            }
        }
    }

    create_dir(_user_dir);
    return _user_dir;
}
...
let cscs_exe: string = path.join(user_dir(), "cscs.exe");
let command = build_command(`"${cscs_exe}" "${file}"`);
let p = exec(command);
...
```

**Comment by AlGantori** [comment]
I just wanted to leave you this hint regarding including the version and other release info summary, check out how this extension is doing it.  You might be able to do the same, I have no experience authoring extension so you are way ahead of me on this topic.

![image](https://user-images.githubusercontent.com/11699920/80307135-1d91a480-877c-11ea-8ad9-47cf686ec6f6.png)

**Comment by oleg-shilo** [comment]
Yes the badges is a good idea. They are simply taken form the GitHub page during the publishing. I have updated GitHub so the badges will be available in VSCode with very next release: 

https://github.com/oleg-shilo/cs-script.vscode/blob/master/README.md
