### ISSUE TITLE
Mono needs to be in the path

### ISSUE THREAD

**Issue by rconde01** [oleg-shilo/cs-script.vscode#2]
...it's not enough for mono to be installed. It needs to be in the path or cs-script.vscode cannot find it. It would be nice for new users to add this to the documentation.

**Comment by oleg-shilo** [comment]
I will add the warning to the doco . Though mono always ads itself during the installation. It's true for both Win and Linux. I never had to do it manually. 

I am puzzled why it's the case for you. The only reason I can come up with is that it is Win and it needs to be restarted or that the Mono installation is somehow incomplete. Both are unlikely but... who knows.

**Comment by oleg-shilo** [comment]
Done.
![image](https://user-images.githubusercontent.com/16729806/29394516-1193ac26-834e-11e7-98cd-7e85f4c50315.png)
