### ISSUE TITLE
Extension Stopped Working after "C# for Visual Studio" extension update

### ISSUE THREAD

**Issue by mmickael** [oleg-shilo/cs-script.vscode#20]
About two weeks ago, "C# for Visual Studio" was updated.   Since then, I get the following error when loading a csharp file:

CS-Script: CS-Script: The required extension "C# for Visual Studio Code" is not found. Ensure it is installed.

The extension is installed.  I tried uninstalling and reinstalling the C# extension, CS-Script, and VS Code itself with no luck.
![Screenshot](https://user-images.githubusercontent.com/13186185/77216461-78364180-6ae8-11ea-9a90-ab9d3dd36efa.jpg)

**Comment by oleg-shilo** [comment]
Thank you.
Yep. Excellent :(
They have changed the name/id of their extension and derailed all extensions that depend on it. Including  CS-Script. This is the checking that is performed at startup:
```C#
if (vscode.extensions.getExtension('ms-vscode.csharp') == null) {
    let message = 'The required extension "C# for Visual Studio Code" is not found. Ensure it is installed.';
    vscode.window.showErrorMessage(message);
    throw message;
}
``` 
And now the extension is effectively missing as they have changed its id to `ms-dotnettools.csharp`.

I will need to update the dependency.

**Comment by mmickael** [comment]
Works now.  Thank you for the quick update.
