### ISSUE TITLE
Version 1.6 Cannot create new script : mono required

### ISSUE THREAD

**Issue by t-andre** [oleg-shilo/cs-script.vscode#21]
OS version : Windows 10

Hi, First of all thank you for the plugin.

If mono is not installed it's not possible  to use the plugin .

I have this error 

**CS-Script: Error: Command failed: mono --version 'mono' is not recognized as an internal or external command, operable program or batch file.**

Cheers.

**Comment by oleg-shilo** [comment]
Yes there is a logical mistake there. Sorry about that.

While mono is not required the check for its presence is still there.

Working on it. The only way around right now is to install Mono :(

**Comment by oleg-shilo** [comment]
Done. Please update to v1.6.1

**Comment by oleg-shilo** [comment]
Fixed. Please update to v1.6.2

**Comment by t-andre** [comment]
Thanks. I will check it

**Comment by t-andre** [comment]
Hi, there's is no mono dependencies error anymore.
But I have a CS-Script initializing error. It's the same problem #22 

Cheers

**Comment by oleg-shilo** [comment]
Please follow #22
I will be publishing updates there.
