### ISSUE TITLE
CS-Script intellisense isn't working

### ISSUE THREAD

**Issue by LuckJmg** [oleg-shilo/cs-script.vscode#23]
Intellisense is not working for me, since no suggestion appears to autocomplete when putting something, I have tried what has occurred to me and I have read but it still does not work.

VSCode v1.44.1 (system setup)
VSCode Extension v1.6.4
CS-Script Engine v3.29.0

**Comment by oleg-shilo** [comment]
The intellisense problems are usually caused by the syntaxer.exe (intellisense provider) not being running.

Can you please start the syntaxer manually and let me know if it throws missing assembly error or similar. Please execute:
```
dotnet C:\Users\<username>\AppData\Roaming\Code\User\cs-script.user\dotnet\syntaxer\syntaxer.core.dll -timeout:60000 -cscs_path:C:\Users\<username>\AppData\Roaming\Code\User\cs-script.user\dotnet\cscs.dll
```

**Comment by LuckJmg** [comment]
In the end it fixed itself, I don't know if it was a problem of some folders that I had, versions of omnisharp or incompatibility, but in the end it was solved itself, unfortunately I can't give you more information since I don't know what it was that fixed it.
Thanks for the help, I hope you are well and thank you very much for this wonderful extension, greetings.
(Sorry for the english, but it is not my native language, I am only 16 years old and I still don't write very well in english although I understand it almost perfectly)

**Comment by oleg-shilo** [comment]
Great, thank you for letting me know.

At startup of any new version of the extension the CS-Script binaries are prepared for the first run of this version. This does take some time during which intellisense is falling back to what ever is offered by VSCode. Quite possibly it was this "first run" problem. 

During the first run initialization the extension is indicating (on the status bar) that it is still initializing. But... the message is easy to miss. And... I did not wan it to be too intrusive as the error messages (toast notifications).
