### ISSUE TITLE
Cannot use //css_ref with brackets even with escape characters

### ISSUE THREAD

**Issue by brogan-ohara** [oleg-shilo/cs-script.vscode#25]
I see this has been fixed in the main engine (https://github.com/oleg-shilo/cs-script/issues/189) but I am still seeing this bug on the VS Code extension.

In my code that I am editing in VS Code, when I save with the line:
"//css_ref C:\Program Files ((x86))\Microsoft Office\Root\Office16\EXCEL.EXE"

the CS-Script pane in the Explorer shows no references.

When I delete the line and save, references appear.

**Comment by oleg-shilo** [comment]
I will need to check but most likely the fixed cs-script engine is not rolled out in this plugin.
Marked it as "enhancement" and address rather soon.

In a mean time you can use this technique:
```
//css_ref  %programfiles(x86)%\Microsoft Office\Root\Office16\EXCEL.EXE
``` 

BTW, I am not sure `excel.exe` is an assembly. I expect it to be a native executable.

**Comment by oleg-shilo** [comment]
Fixed in he latest CS-Script engine release
