### ISSUE TITLE
Encoding issue in output window 

### ISSUE THREAD

**Issue by Chinese-Xu** [oleg-shilo/cs-script.vscode#29]
Hi

It may a encoding issue.  My OS is win10 CHS. 
![image](https://user-images.githubusercontent.com/2484031/150631633-89aa22ba-4b3f-475a-aea5-5aa38839f8ba.png)

**Comment by oleg-shilo** [comment]
You can check your encoding with 
```
css -config:get:ConsoleEncoding
```

and you can set it to the desired one (e.g. UTF8) with. 
```
css -config:set:ConsoleEncoding=UTF8
```
If you do not have CS-Script installed then you need to replace `css` with `dotnet <path to cscs.dll>`.

And you can also use envars for that system-wide: `CSSCRIPT_CONSOLE_ENCODING_OVERWRITE`

BTW this sort of problems can also araise from the inadequate font being used in the Debig Console. But I do not know how you can control it

**Comment by Chinese-Xu** [comment]
Thanks for your help
The issue resolved by `css -config:set:ConsoleEncoding=UTF8`

**Comment by Chinese-Xu** [comment]
Thanks
