### ISSUE TITLE
extension not installing in vs code

### ISSUE THREAD

**Issue by foobar41** [oleg-shilo/cs-script.vscode#31]
Giving a lot of errors in the log file when trying to install the extension

Steps to reproduce:
-- Install the VS Code extension at [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=oleg-shilo.cs-script)

**Comment by oleg-shilo** [comment]
Can you elaborate, please? What is the log file and what are the errors?
I was not able to reproduce the problem with the steps you described. The least latest VSCode installs the extension without any problems:
![image](https://user-images.githubusercontent.com/16729806/175777628-130bed11-63e6-4248-9710-573513874eb4.png)

**Comment by foobar41** [comment]
It seems to be working now. Maybe I had a connection issue, sorry for the inconvenience

**Comment by oleg-shilo** [comment]
Not a problem. Glad it all worked out.
