### ISSUE TITLE
Is there a way to specify debug command line arguments?

### ISSUE THREAD

**Issue by rconde01** [oleg-shilo/cs-script.vscode#6]
No sure if I'm missing it or if it's not there....if not...it would be nice :)

**Comment by oleg-shilo** [comment]
Yes there is a way.  Though is't not part of the VSCode story but a CS-Script one. 
CS-Script allows you to specify the arguments directly in the script with the `//css_args` directive. It's particularly useful during an active development or troubleshooting. 

![image](https://user-images.githubusercontent.com/16729806/29593915-953ad6ca-87f0-11e7-9eb1-618da3ebe322.png)

**Comment by rconde01** [comment]
That works! Thanks.
