### ISSUE TITLE
script debugging not working anymore

### ISSUE THREAD

**Issue by psrivastava** [oleg-shilo/cs-script.vscode#8]
seems related to recent commit "- Added tunneling `StartDebug` request when workspace is loaded"

Now, trying ctrl+F5 just launches the .NET Core debugger and not Mono cs-script debugger anymore.
If I run the script with no .vscode folder, it prompts to create one & still wont start a mono based csscript debugger.

**Comment by psrivastava** [comment]
This is working Oleg. 
My issue is specific to folder open.   I have a top level .netcore project to turn on intellisense.
Then I just use cs-script to individually run the scripts.

a week or two ago, even in this scenario,  mono-debug would start using the cs-script debug option, all by itself.
Now, like you said, only launch configs[0]  is invoked, which is true, I have .NET core.

but note, I don't have any cs-script lunch settings in my json either.

**Comment by psrivastava** [comment]
btw, I got something going for myself by manually adding a 'cs-script' launch settings in my launch.json & making it first entry in the list.

` {
            "name": "CS-Script (console)",
            "type": "mono",
            "request": "launch",
            "program": "${env:APPDATA}/Code/User/cs-script.user/cscs.exe",
            "args": ["-d", "-inmem:0", "-co:/debug:pdbonly", "-ac:2", "${file}"],
            "cwd": "${fileDirname}",
            "console": "internalConsole"
        }
`

**Comment by oleg-shilo** [comment]
Yes it is one of the possible solutions.

Another one is to use coderunner extension
```json
"code-runner.executorMap": {
    "csharp": "%CSSCRIPT_DIR%/cscs -noconfig -nl"...
  },
```
I will prepare a hotfix release to allow disabling tunneling and allowing (optionally) starting debugging cs-script with a workspace loaded. 

I do prefer disabling debugging the workspaces as it creates certain ambiguity. But I have no problems with users enabling it when they choose to.

**Comment by oleg-shilo** [comment]
Done. The new release v1.5.2 has the behavior you want by default. Any variation to it is done via user custom settings file.
